version: '3.9'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
        volumes:
            - ./html:/var/www/html
        links:
            - mariadb
    mariadb:
        build:
            context: ./mariadb
        volumes:
            - ./mariadb/mariadb_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mariadb